version: "3.2"
services:
  product-service:
    container_name: product-service
    image: product-service
    build:
      context: '.'
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/var/app
      - ./.docker/start.sh:/usr/local/bin/start.sh
    depends_on:
      - product-database
  product-database:
    container_name: product-database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - product-data:/var/lib/mysql
  product-adminer:
    container_name: product-adminer
    image: adminer
    restart: always
    environment: 
        ADMINER_DEFAULT_SERVER: product-database
    ports:
      - ${ADMINER_PORT}:8080
volumes:
  product-data:
